### Site Settings ###
title               : Yusuf SEZER
description         : >-                               # >- means to ignore newlines until "url:"
                      Software developer, interested about web technologies, algorithms, artificial intelligence and embedded systems; constantly exploring new technologies.

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/portfolYOU"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : yusufsefasezer/yusufsefasezer.github.io    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]


### Navbar Settings ###
nav_exclude:                        # Pages with the following paths will be excluded from navbar
  - 404.html
  - index.html
  - blog/tags.html
  - blog/page-:num/index.html


### Author Info ###
author:
  name              : Yusuf SEZER
  image             : assets/images/yusuf-sezer.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : yusufsezer@mail.com
#  facebook          : your_username
  github            : yusufsefasezer
# gitlab            : your_username
# instagram         : your_username
  linkedin          : yusufsefasezer
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : yusufsefasezer
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/blog/page-:num/"


### Posts Permalink ###
permalink: :title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Plugins ###
plugins:
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-paginate
  - jemoji


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - portfolyou-jekyll-theme.gemspec
  - "*.log"
